### PR TITLE
Don't prompt on CI

### PR DESCRIPTION
**Pull request by x2on**
I run into a problem, that the plugin was prompting on CI what doesn't work at all.
So i deactivated that if on Travis or Teamcity.

### CODE REVIEW

**Comment by orta** [comment]
Throw in a check for `CIRCLECI` and you've got yourself a merge!

**Comment by x2on** [comment]
Done.
Probably the `ENV` part should be moved outside the keychain stuff in the future... What do you think?

**Comment by orta** [comment]
Yeah, could move having two separate read sources, ENV & keychain

**Comment by orta** [comment]
oh rubocop, you've obviously made too complex of a function @x2on  ;)

**Comment by x2on** [comment]
I will move it :)

**Comment by orta** [comment]
Thanks @x2on !

**Comment by x2on** [comment]
Just fixing our environment :) Thanks for that great plugin.

**Comment by orta** [comment]
released 1.5.2 with this

**Pull request merged**
