### PR TITLE
Add support for Ventura and M1 | osx_keychain to ruby-keychain

### PR DESCRIPTION
**Pull request by tritter**
I rewrote the `keychain.rb` file to use the ruby keychain plugin, which works also on m1 machines. And removes the broken dependency on ruby_inline.

What has been done:
• Updated dependencies (and ruby to 2.7.4 native m1 supported)
• Updated rubocop
• Moved keychain.rb logic from osx_keychain to ruby_keychain
• Updated tests

### CODE REVIEW

**Comment by orta** [comment]
Looks pretty solid to me, there's no tests on this repo so maybe just give it a run in your own app a bit to verify 👍🏻

**Comment by tritter** [comment]
@orta yes that's why its in draft I still need to test on some intel machines and m1 machines with keychains generated with the osx_keychain.

**Comment by tritter** [comment]
Just tested with intel. Clean install and on an older cocoapods version. Working perfectly so also with existing secrets! :) I just had a tiny dependency issue before.

Who wants to test this can install this into your project's Gemfile:
`gem 'cocoapods-keys', git: 'https://github.com/tritter/cocoapods-keys.git'`

**Comment by orta** [comment]
Greeat!

**Comment by orta** [comment]
Thanks, this is deployed as 2.3.0!

**Pull request merged**
