### PR TITLE
Better error handling in lib/key_master.rb; resolves #67

### LINKED ISSUE #67: CocoaPods-keys fails when a key/value pair is nil
The issue stems from that CocoaPods-keys doesn’t consider what keys the user loads in the Podfile, but instead looks at what keys the user set for the whole project. So if a user were to remove a key *just* in the keychain, the associated project key wouldn’t be removed. Any sort of `pod` command that modifies the project would then fail with the error below.

Notice that I don’t ever reference the a null key in the Podfile (`ParseAppID` and `ParseClientSecret` have associated keys in the keychain). When I `pod keys rm` the key without the associated key in the keychain, the issue went away.

The following commands are another, simpler demonstration.

```
$ pod keys set "test" "test"
Saved test to Boards.
$ pod keys get test
test
```
At this point, the key "test" is removed from the the keychain.
```
$ pod keys get test

$
```

(This is probably just an issue related to misuse of cocoapods-keys, but the resulting error can be confusing. If there’s any interest, I could open a pull request that fixes the bug.)

***

### Command

```
/Users/David/.rbenv/versions/2.2.2/bin/pod install
```

### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3.1 (6D1002)
         Git : git version 2.2.1
Ruby lib dir : /Users/David/.rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 36995f6671994dbd159fee66aadfe62aee1c94e3
```

### Plugins

```
cocoapods-keys    : 1.2.0
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.4
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs'
use_frameworks!

platform :ios, '8.0'

plugin 'cocoapods-keys', {
  :project => "Boards",
  :keys => [
    "ParseAppID",
    "ParseClientSecret"
]}

# Add Application pods here
pod 'Parse'
pod 'ReactiveCocoa'
pod 'JTSScrollIndicator'
pod 'RAReorderableLayout'
pod 'ionicons'

target :unit_tests, :exclusive => true do
  link_with 'UnitTests'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
  pod 'OHHTTPStubs'
end


# Copy acknowledgements to the Settings.bundle

post_install do | installer |
  require 'fileutils'

  pods_acknowledgements_path = 'Pods/Target Support Files/Pods/Pods-Acknowledgements.plist'
  settings_bundle_path = Dir.glob("**/*Settings.bundle*").first

  if File.file?(pods_acknowledgements_path)
    puts 'Copying acknowledgements to Settings.bundle'
    FileUtils.cp_r(pods_acknowledgements_path, "#{settings_bundle_path}/Acknowledgements.plist", :remove_destination => true)
  end
end
```

### Error

```
NoMethodError - undefined method `length' for nil:NilClass
/Users/David/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-keys-1.2.0/lib/key_master.rb:26:in `map'
/Users/David/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-keys-1.2.0/lib/key_master.rb:26:in `generate_data'
/Users/David/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-keys-1.2.0/lib/key_master.rb:16:in `initialize'
/Users/David/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-keys-1.2.0/lib/plugin.rb:23:in `new'
/Users/David/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-keys-1.2.0/lib/plugin.rb:23:in `setup'
/Users/David/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-keys-1.2.0/lib/plugin.rb:72:in `install!'
/Users/David/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/David/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:101:in `run'
/Users/David/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/David/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Users/David/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/Users/David/.rbenv/versions/2.2.2/bin/pod:23:in `load'
/Users/David/.rbenv/versions/2.2.2/bin/pod:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by davidbarsky**
Previously, if `keyring.keychain_data` in `/lib/key_master.rb` had anything that was nil, there would be a weird runtime exception as documented in #67. Instead, a slightly more informative error is given to the user.

### CODE REVIEW

**Comment by davidbarsky** [comment]
That... was my bad. Didn’t run the tests before opening a pull request, sorry about that. There’s a very good chance I misunderstood how `key_master.rb` is implemented, as allowing the KeyMaster to work with an empty keyring *is* the source of the issue of #67.

I don’t want to make any more changes without consulting someone more qualified on the matter.

**Comment by orta** [comment]
OK, so some of this logic in the tests aren't needed anymore, this was done to try and ensure that it would run fine on projects that didn't use keys. Now we check that there's a reference to the plugin in the Podfile. 

They can be deleted.

**Comment by orta** [comment]
Oh, sorry! This is unmergable, just noticed that you fixed the tests!

**Comment by davidbarsky** [comment]
No worries! I’ve just resolved those conflicts.

**Comment by orta** [comment]
Its looking like the merge has tests in which the `raise` isn't handled anymore, any chance you can take a look? Sorry for all the messing around

**Comment by davidbarsky** [comment]
no worries, i mistyped a `.any?` call in the checker; my mistake. tests (of what few remain) pass.

**Comment by orta** [comment]
oh nice, and colour'd tests :dancers:

**Comment by orta** [comment]
Thanks @davidbarsky

**Pull request merged**
