### PR TITLE
Fix Keys.m generation when there are empty-string keys

### LINKED ISSUE #203: ZillyKeys.m doesn't compile with "Expected expression" error
[After adding `gem rake` to our Gemfile](https://github.com/fastlane/fastlane/issues/16725#issuecomment-652778837) and upgrading fastlane from 2.150.0rc1 to 2.150.0, it stopped compiling when the key is an empty string `""`:

image

Removing the extra highlighted comma fixes the compilation issue.

It works fine if the key is not an empty string (but we require this empty string key in our current environment).

I know rake and fastlane are not directly related to this pod, but I'm just trying to provide more information that could help debugging this issue. There are other fastlane dependencies that were upgraded in release 2.150.0.

### PR DESCRIPTION
**Pull request by rogerluan**
Resolves #203

### CODE REVIEW

**Comment by rogerluan** [comment]
CI is failing, but it's failing in master too 😬 @ashfurrow

**Comment by rogerluan** [comment]
> Looks good 👍 Aye, CI on master could use work. I'll try to get to that this weekend.
> 
> Have you tested this locally? You can do this by modifying your Gemfile:
> 
> ```diff
> - gem 'cocoapods-keys'
> + gem 'cocoapods-keys', git: 'https://github.com/rogerluan/cocoapods-keys.git'
> ```
> 
> And re-run `bundle install` and `bundle exec pod install`, and that should do it.

I did yeah, using `path:` while developing, and then committed this to my project:

```diff
-gem 'cocoapods-keys', '2.1.0'
+gem 'cocoapods-keys', '2.2.1', github: 'rogerluan/cocoapods-keys', branch: 'master'
```

It works 🚀

**Comment by ashfurrow** [comment]
Awesome! @orta would you like to add me as an owner to the gem in RubyGems.org and I can handle publishing?

**Comment by orta** [comment]
You're on!

**Comment by ashfurrow** [comment]
Thank you @orta :bow: 

Alrighty! Thanks again @rogerluan – I've pushed that as version 2.2.1 to RubyGems. Please get in touch if you find any other issues!

**Comment by rogerluan** [comment]
Thanks! ❤️

**Pull request merged**
