### PR TITLE
Adding missing "generate" command

### PR DESCRIPTION
**Pull request by robbiehanson**
This command was listed in the readme, but was missing from the project.
Fixes issue #91

### CODE REVIEW

**Comment by orta** [comment]
Sorry this took a while, problem is also rubocop ;)

**Comment by orta** [comment]
Looks good otherwise 👍

**Comment by orta** [comment]
Cool, thanks, added you as a collaborator too - no pressure, but allows you some control if somethings taking a while. I have a lot of projects to juggle.

**Comment by robbiehanson** [comment]
> added you as a collaborator too - no pressure

Thanks. My ruby isn't the best though, so if I'm unsure of anything I'll use a separate branch for review.

> I have a lot of projects to juggle.

I understand. I'm in a similar boat.

**Pull request merged**
