### PR TITLE
Initial unit tests for KeyMaster

### PR DESCRIPTION
**Pull request by lyricsboy**
Extracts objc output into standalone ERB template files. I have not tested the packaging and distribution of this gem with those files included.

Adds tests to ensure that:

* KeyMaster produces reasonable files when given no keys
* Those files syntax check with clang

The structure is in place to easily support testing actual key generation output with additional fixture files.

One challenge will be in mocking the use of the random number generators. Ruby's `rand` can be seeded with `srand 1234` to produce consistent results, but the trip through `/dev/random` in the shell is not mockable directly. That input source could be extracted into a Ruby IO object to make it deterministic in test.

### CODE REVIEW

**Comment by orta** [comment]
This is awesome! Will give it a good look in the evening

**Comment by lyricsboy** [comment]
Thanks y'all. We should consider adding explicit version requirements for Ruby and RSpec to the gemspec. This code relies on RSpec 3+ and Ruby 1.9+ (at least).

**Comment by segiddins** [comment]
Fwiw, in CocoaPods we use bacon instead of Rspec, and it would be nice to stay consistent. Additionally, we only add testing dependencies to the Gemfile, and not the Gemspec.

**Comment by orta** [comment]
That's fair @segiddins, but I'm definitely not turning away someone who has actually started a test suite :star:

**Pull request merged**
