### PR TITLE
Check for project names that start with number

### PR DESCRIPTION
**Pull request by anurlybayev**

### CODE REVIEW

**Comment by orta** [comment]
Any chance we can get a test for this please @anurlybayev - it could easily get clobbered in a later commit

**Comment by anurlybayev** [comment]
@orta let me see what I can do. Rubylang is completely new to me...

**Comment by anurlybayev** [comment]
@orta anything else you need from me?

**Comment by orta** [comment]
No, this looks perfect, sorry been away all weekend!

**Comment by orta** [comment]
Great work on the tests :dancers:

**Pull request merged**
