### PR TITLE
Prepare for 1.8.0

### PR DESCRIPTION
**Pull request by orta**
Waiting on https://github.com/orta/cocoapods-keys/issues/154 before releasing though

### CODE REVIEW

**Comment by Skogetroll** [comment]
@orta is it ready for release now?

**Comment by orta** [comment]
yeah, we got 2 breaking changes in here, so I've bumped it to 2.0 instead

**Comment by orta** [comment]
Just waiting on green

**Comment by orta** [comment]
The red is not coming, it's a ruby issue though, I'm alright with this

**Pull request merged**
